extends: '@esperecyan'

env:
    es6: false

globals:
    REM: true
    WSH: false
    Enumerator: false
    jsyaml: false

rules:
    no-var: off

    strict: ['warn', 'never']

    new-cap: off
    comma-dangle: ['warn', {arrays: always-multiline, objects: always-multiline}]
